'use client';

import { ArrowRight, Loader2 } from 'lucide-react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useCallback, useState } from 'react';
import { toast } from 'sonner';

import { usePasswordStrength } from '@/shared/auth/hooks/usePasswordStrength';
import { type ApiError, getApiErrorMessage, resetPassword } from '@/shared/lib/auth';
import { AuthCard } from '@/site/components/auth/AuthCard';
import { AuthHeader } from '@/site/components/auth/AuthHeader';
import { AuthPageLayout } from '@/site/components/auth/AuthPageLayout';
import { PasswordStrengthGuidance } from '@/site/components/auth/PasswordStrengthGuidance';
import { AuthSubmitButton } from '@/site/components/auth/AuthSubmitButton';
import { PasswordField } from '@/site/components/auth/FormFields';

/**
 * Password Reset Route
 *
 * Handles the password reset flow after user clicks the reset link from email.
 * The reset token is passed via URL query parameter (generated by backend as JWT).
 *
 * Flow:
 * 1. User receives reset link in email: /auth/reset-password?token=JWT_TOKEN
 * 2. User enters new password (with confirmation)
 * 3. Token + password is sent to backend
 * 4. Backend validates token and updates password
 * 5. User redirected to login to sign in with new password
 */
export function ResetPasswordRoute() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const token = searchParams.get('token') ?? '';

  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [isLoading, setIsLoading] = useState(false);
  const passwordStrength = usePasswordStrength(password);

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();

      // Validate token exists
      if (!token) {
        toast.error('Invalid reset link. Token is missing.');
        return;
      }

      // Validate passwords match
      if (password !== confirmPassword) {
        setFieldErrors({ confirmPassword: 'Passwords do not match.' });
        return;
      }

      // Validate password not empty
      if (!password.trim()) {
        setFieldErrors({ password: 'Password is required.' });
        return;
      }

      if (!passwordStrength?.isStrong) {
        setFieldErrors({ password: 'Choose a stronger password before continuing.' });
        return;
      }

      setFieldErrors({});
      setIsLoading(true);

      try {
        const result = await resetPassword(token, password);

        if (result.status) {
          toast.success('Password reset successfully. Please sign in with your new password.');
          router.replace('/auth/login');
        } else {
          toast.error('Failed to reset password. Please try again.');
        }
      } catch (err) {
        const apiErr = err as ApiError;
        const message = getApiErrorMessage(
          err,
          apiErr.status === 400 || apiErr.status === 422
            ? 'Password reset failed. Please check your reset link and try again.'
            : 'Password reset failed. Please try again.'
        );

        // Handle specific error cases
        if (apiErr.detail?.includes?.('expired') || apiErr.detail?.includes?.('invalid')) {
          toast.error('Your reset link has expired. Please request a new one.');
        } else if (apiErr.code === 'AUTH_WEAK_PASSWORD' || apiErr.detail?.includes?.('password')) {
          setFieldErrors({
            password:
              typeof apiErr.detail === 'string'
                ? apiErr.detail
                : 'Password does not meet requirements. Please try a different password.',
          });
        } else {
          toast.error(message);
        }
      } finally {
        setIsLoading(false);
      }
    },
    [token, password, confirmPassword, router]
  );

  // Show error if no token
  if (!token) {
    return (
      <AuthPageLayout>
        <AuthHeader mode="login" />
        <AuthCard>
          <div className="space-y-4">
            <h2 className="font-mono text-sm uppercase tracking-wider text-nexus-light">
              Invalid Reset Link
            </h2>
            <p className="font-mono text-xs text-nexus-muted">
              The password reset link is invalid or has expired. Please request a new one.
            </p>
            <div className="pt-4 flex gap-3">
              <Link
                href="/auth/forgot-password"
                className="flex-1 text-center font-mono text-xs text-nexus-muted hover:text-nexus-purple underline decoration-dotted underline-offset-4 transition-colors uppercase tracking-wider"
              >
                Request new reset link
              </Link>
              <Link
                href="/auth/login"
                className="flex-1 text-center font-mono text-xs text-nexus-muted hover:text-nexus-purple underline decoration-dotted underline-offset-4 transition-colors uppercase tracking-wider"
              >
                Back to login
              </Link>
            </div>
          </div>
        </AuthCard>
      </AuthPageLayout>
    );
  }

  return (
    <AuthPageLayout>
      <AuthHeader mode="login" />

      <AuthCard>
        <div className="mb-6 text-center">
          <h2 className="font-mono text-sm uppercase tracking-wider text-nexus-light">
            Reset password
          </h2>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* New Password */}
          <PasswordField
            value={password}
            onChange={(value) => {
              setPassword(value);
              setFieldErrors((current) => {
                if (!current.password) return current;
                const next = { ...current };
                delete next.password;
                return next;
              });
            }}
            label="New Password"
            error={!!fieldErrors.password}
            required
          />
          <PasswordStrengthGuidance
            strength={passwordStrength}
            error={fieldErrors.password}
          />

          {/* Confirm Password */}
          <PasswordField
            value={confirmPassword}
            onChange={(val) => {
              setConfirmPassword(val);
              setFieldErrors((current) => {
                if (!current.confirmPassword) return current;
                const next = { ...current };
                delete next.confirmPassword;
                return next;
              });
            }}
            label="Confirm Password"
            error={!!fieldErrors.confirmPassword}
            required
          />

          {fieldErrors.confirmPassword ? (
            <p className="font-mono text-xs text-red-500">{fieldErrors.confirmPassword}</p>
          ) : null}

          {/* Submit Button */}
          <AuthSubmitButton type="submit" disabled={isLoading}>
            {isLoading ? (
              <>
                <Loader2 size={18} className="animate-spin shrink-0" />
                <span>RESETTING...</span>
              </>
            ) : (
              <>
                RESET PASSWORD <ArrowRight size={16} />
              </>
            )}
          </AuthSubmitButton>
        </form>

        <div className="mt-6 text-center space-y-2">
          <Link
            href="/auth/login"
            className="block font-mono text-xs text-nexus-muted hover:text-nexus-purple underline decoration-dotted underline-offset-4 transition-colors uppercase tracking-wider"
          >
            Back to login
          </Link>
        </div>
      </AuthCard>
    </AuthPageLayout>
  );
}
