'use client';

import Link from 'next/link';
import { Check, Globe, Lock, Terminal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
import type { Template } from '@/shared/types';

import { DashboardPageHeader, PageLayout } from '@/dashboard/components';
import { useAuth } from '@/shared/auth';
import { createProject } from '@/shared/lib/projects';
import { queryKeys } from '@/shared/lib/query-keys';
import { Button } from '@/ui/shadcn/ui/button';
import { Card, CardContent } from '@/ui/shadcn/ui/card';
import { Input } from '@/ui/shadcn/ui/input';
import { Label } from '@/ui/shadcn/ui/label';
import { Textarea } from '@/ui/shadcn/ui/textarea';
import { toast } from '@/ui/system';

type ProjectVisibility = 'private' | 'public';
type StepId = 'details' | 'template' | 'review';

const STEPS = [
  { id: 'details', title: 'Details', description: 'Name and visibility' },
  { id: 'template', title: 'Template', description: 'Choose a starter' },
  { id: 'review', title: 'Review', description: 'Confirm and create' },
] as const;
interface NewProjectRouteProps {
  templates: Template[];
}

export const NewProjectRoute = ({ templates }: NewProjectRouteProps) => {
  const router = useRouter();
  const queryClient = useQueryClient();
  const { user, hydrated } = useAuth();
  const [projectName, setProjectName] = useState('');
  const [description, setDescription] = useState('');
  const [visibility, setVisibility] = useState<ProjectVisibility>('private');
  const [autoGeneratedName, setAutoGeneratedName] = useState(false);
  const [currentStep, setCurrentStep] = useState<0 | 1 | 2>(0);
  const [autoSelectTemplate, setAutoSelectTemplate] = useState(true);
  const [selectedTemplate, setSelectedTemplate] = useState<string>(templates[0]?.id ?? '');

  const canContinueFromDetails = useMemo(
    () =>
      autoGeneratedName
        ? description.trim().length > 0
        : projectName.trim().length > 0,
    [autoGeneratedName, projectName, description]
  );
  const canContinueFromTemplate = useMemo(
    () => autoSelectTemplate || Boolean(selectedTemplate),
    [autoSelectTemplate, selectedTemplate]
  );
  const activeStepId = STEPS[currentStep]?.id as StepId;
  const selectedTemplateInfo = useMemo(
    () => templates.find(t => t.id === selectedTemplate) ?? templates[0],
    [templates, selectedTemplate]
  );

  const slugify = (value: string) =>
    value
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-');

  const generateNameFromPrompt = (prompt: string) => {
    const cleaned = prompt
      .replace(/[^a-zA-Z0-9\s-]/g, ' ')
      .trim()
      .split(/\s+/)
      .slice(0, 3)
      .join(' ');

    if (cleaned.length > 0) {
      return cleaned
        .split(' ')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join(' ');
    }

    return `Untitled Project ${new Date().toISOString().slice(0, 10)}`;
  };

  const createProjectMutation = useMutation({
    mutationFn: async () => {
      if (!hydrated || !user) throw new Error('You must be signed in to create a project.');

      const trimmedDescription = description.trim();
      const finalName = autoGeneratedName
        ? generateNameFromPrompt(trimmedDescription)
        : projectName.trim();
      const finalSlug = slugify(finalName);

      if (!finalName) throw new Error('Project name is required.');
      if (autoGeneratedName && !trimmedDescription) {
        throw new Error('Please describe the project so the agent can generate its name.');
      }

      return createProject(undefined, {
        name: finalName,
        slug: finalSlug || undefined,
      });
    },
    onSuccess: async project => {
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: queryKeys.projects('active') }),
        queryClient.invalidateQueries({ queryKey: queryKeys.projects('archived') }),
        queryClient.invalidateQueries({ queryKey: queryKeys.projects('all') }),
      ]);
      toast.success('Project created successfully.');
      router.push(`/editor/${project.id}`);
    },
    onError: error => {
      const message = error instanceof Error ? error.message : 'Failed to create project.';
      toast.error(message);
    },
  });

  const handleContinue = () => {
    if (currentStep === 0 && canContinueFromDetails) {
      setCurrentStep(1);
      return;
    }
    if (currentStep === 1 && canContinueFromTemplate) {
      setCurrentStep(2);
    }
  };

  const handleBack = () => {
    if (currentStep > 0) setCurrentStep((prev => (prev - 1) as 0 | 1 | 2));
  };

  return (
    <PageLayout className="pb-12">
      <DashboardPageHeader
        badge={{ icon: Terminal, label: 'PROJECTS' }}
        title="Create a new project"
        subtitle="Set up your project details to get started."
        actions={
          <Button asChild variant="destructive">
            <Link href="/dashboard">Cancel</Link>
          </Button>
        }
      />

      <div className="mt-8">
        <Card className="overflow-hidden border-border/80 bg-card/80 backdrop-blur-sm">
          <div className="grid items-start gap-6 lg:grid-cols-[260px_minmax(0,1fr)] lg:gap-0">
            <aside className="hidden lg:block lg:px-6 lg:py-8">
              <div className="w-full">
                <h3 className="pt-1 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Steps
                </h3>
                <div className="relative mt-6 space-y-7 before:absolute before:bottom-3 before:left-3 before:top-3 before:w-px before:bg-border">
                  {STEPS.map((step, index) => {
                    const isActive = index === currentStep;
                    const isDone = index < currentStep;

                    return (
                      <div key={step.id} className="relative flex items-start gap-4">
                        <div
                          className={[
                            'relative z-10 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border-2 bg-background text-xs font-medium transition-colors',
                            isActive
                              ? 'border-primary text-primary'
                              : isDone
                                ? 'border-primary bg-primary text-primary-foreground'
                                : 'border-muted text-muted-foreground',
                          ].join(' ')}
                        >
                          {isDone ? <Check className="h-3 w-3" /> : index + 1}
                        </div>
                        <div className="flex flex-col">
                          <span
                            className={[
                              'text-sm font-medium leading-none',
                              isActive ? 'text-foreground' : 'text-muted-foreground',
                            ].join(' ')}
                          >
                            {step.title}
                          </span>
                          <span className="mt-1.5 text-xs text-muted-foreground">
                            {step.description}
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </aside>

            <CardContent className="min-w-0 p-6 md:p-8 lg:border-l lg:border-border/80">
              <div className="mb-6 space-y-2 lg:hidden">
                <div className="flex items-center justify-between text-sm font-medium">
                  <span>
                    Step {currentStep + 1} of {STEPS.length}
                  </span>
                  <span className="text-muted-foreground">{STEPS[currentStep].title}</span>
                </div>
                <div className="h-2 w-full overflow-hidden rounded-full bg-secondary">
                  <div
                    className="h-full rounded-full bg-primary transition-all"
                    style={{ width: `${((currentStep + 1) / STEPS.length) * 100}%` }}
                  />
                </div>
              </div>

              <div className="space-y-8">
                {activeStepId === 'details' && (
                  <>
                    <div>
                      <h2 className="text-2xl font-semibold tracking-tight">Project Details</h2>
                      <p className="mt-1 text-sm text-muted-foreground">
                        Set your project name, write a short description, and choose visibility.
                      </p>
                    </div>

                    <div className="space-y-6">
                      <div className="space-y-2">
                        <Label htmlFor="project-name" className="text-sm font-medium">
                          Project Name <span className="text-destructive">*</span>
                        </Label>
                        <div className="flex max-w-2xl items-center gap-3">
                          <Input
                            id="project-name"
                            value={projectName}
                            onChange={e => setProjectName(e.target.value)}
                            placeholder={
                              autoGeneratedName
                                ? 'Will be generated by the agent from your prompt'
                                : 'e.g. my-awesome-project'
                            }
                            disabled={autoGeneratedName}
                            className="max-w-md"
                          />
                          <label className="inline-flex items-center gap-2 text-sm text-muted-foreground">
                            <input
                              type="checkbox"
                              checked={autoGeneratedName}
                              onChange={e => {
                                const checked = e.target.checked;
                                setAutoGeneratedName(checked);
                                if (checked) setProjectName('');
                              }}
                              className="size-4 accent-primary"
                            />
                            Auto generated
                          </label>
                        </div>
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="project-description" className="text-sm font-medium">
                          Description{' '}
                          <span className="font-normal text-muted-foreground">
                            {autoGeneratedName ? '(Required for auto-generated name)' : '(Optional)'}
                          </span>
                        </Label>
                        <Textarea
                          id="project-description"
                          value={description}
                          onChange={e => setDescription(e.target.value)}
                          placeholder="Describe what this project will do..."
                          className="min-h-[120px] max-w-2xl resize-y"
                        />
                      </div>

                      <div className="space-y-3">
                        <Label className="text-sm font-medium">Visibility</Label>
                        <div className="grid max-w-2xl gap-4 sm:grid-cols-2">
                          <label
                            className={[
                              'relative flex cursor-pointer flex-col gap-4 rounded-lg border p-4 transition-colors hover:bg-accent/50',
                              visibility === 'private'
                                ? 'border-primary bg-primary/5 ring-1 ring-primary'
                                : 'border-border',
                            ].join(' ')}
                          >
                            <div className="flex items-center justify-between">
                              <div className="flex items-center gap-2">
                                <Lock className="h-4 w-4 text-muted-foreground" />
                                <span className="text-sm font-medium">Private</span>
                              </div>
                              <div
                                className={[
                                  'flex h-4 w-4 items-center justify-center rounded-full border',
                                  visibility === 'private' ? 'border-primary' : 'border-muted-foreground/30',
                                ].join(' ')}
                              >
                                {visibility === 'private' && (
                                  <div className="h-2 w-2 rounded-full bg-primary" />
                                )}
                              </div>
                            </div>
                            <p className="text-xs leading-relaxed text-muted-foreground">
                              Only you and invited members can view and collaborate on this project.
                            </p>
                            <input
                              type="radio"
                              name="visibility"
                              value="private"
                              className="sr-only"
                              checked={visibility === 'private'}
                              onChange={() => setVisibility('private')}
                            />
                          </label>

                          <label
                            className={[
                              'relative flex cursor-pointer flex-col gap-4 rounded-lg border p-4 transition-colors hover:bg-accent/50',
                              visibility === 'public'
                                ? 'border-primary bg-primary/5 ring-1 ring-primary'
                                : 'border-border',
                            ].join(' ')}
                          >
                            <div className="flex items-center justify-between">
                              <div className="flex items-center gap-2">
                                <Globe className="h-4 w-4 text-muted-foreground" />
                                <span className="text-sm font-medium">Public</span>
                              </div>
                              <div
                                className={[
                                  'flex h-4 w-4 items-center justify-center rounded-full border',
                                  visibility === 'public' ? 'border-primary' : 'border-muted-foreground/30',
                                ].join(' ')}
                              >
                                {visibility === 'public' && (
                                  <div className="h-2 w-2 rounded-full bg-primary" />
                                )}
                              </div>
                            </div>
                            <p className="text-xs leading-relaxed text-muted-foreground">
                              Anyone on the internet can view this project. Only invited members can edit.
                            </p>
                            <input
                              type="radio"
                              name="visibility"
                              value="public"
                              className="sr-only"
                              checked={visibility === 'public'}
                              onChange={() => setVisibility('public')}
                            />
                          </label>
                        </div>
                      </div>
                    </div>
                  </>
                )}

                {activeStepId === 'template' && (
                  <>
                    <div>
                      <h2 className="text-2xl font-semibold tracking-tight">Choose a Template</h2>
                      <p className="mt-1 text-sm text-muted-foreground">
                        Pick a starter template for your new project.
                      </p>
                    </div>
                    <div className="max-w-3xl space-y-4">
                      <label className="inline-flex items-center gap-2 text-sm text-muted-foreground">
                        <input
                          type="checkbox"
                          checked={autoSelectTemplate}
                          onChange={e => {
                            const checked = e.target.checked;
                            setAutoSelectTemplate(checked);
                            if (checked) {
                              setSelectedTemplate(templates[0]?.id ?? '');
                            }
                          }}
                          className="size-4 accent-primary"
                        />
                        Auto select best template
                      </label>

                      <div className="grid gap-4 md:grid-cols-2">
                      {templates.map(template => (
                        <label
                          key={template.id}
                          className={[
                            'relative flex cursor-pointer flex-col gap-2 rounded-lg border p-4 transition-colors hover:bg-accent/50',
                            !autoSelectTemplate && selectedTemplate === template.id
                              ? 'border-primary bg-primary/5 ring-1 ring-primary'
                              : 'border-border',
                            autoSelectTemplate ? 'opacity-60' : '',
                          ].join(' ')}
                        >
                          <div className="flex items-center justify-between gap-3">
                            <span className="text-sm font-medium">{template.title}</span>
                            <div
                              className={[
                                'flex h-4 w-4 items-center justify-center rounded-full border',
                                !autoSelectTemplate && selectedTemplate === template.id
                                  ? 'border-primary'
                                  : 'border-muted-foreground/30',
                              ].join(' ')}
                            >
                              {!autoSelectTemplate && selectedTemplate === template.id && (
                                <div className="h-2 w-2 rounded-full bg-primary" />
                              )}
                            </div>
                          </div>
                          <p className="text-xs text-muted-foreground">{template.description}</p>
                          <input
                            type="radio"
                            name="template"
                            value={template.id}
                            checked={selectedTemplate === template.id}
                            onChange={() => {
                              setAutoSelectTemplate(false);
                              setSelectedTemplate(template.id);
                            }}
                            disabled={autoSelectTemplate}
                            className="sr-only"
                          />
                        </label>
                      ))}
                      </div>
                    </div>
                  </>
                )}

                {activeStepId === 'review' && (
                  <>
                    <div>
                      <h2 className="text-2xl font-semibold tracking-tight">Review</h2>
                      <p className="mt-1 text-sm text-muted-foreground">
                        Confirm your project setup before creation.
                      </p>
                    </div>
                    <div className="max-w-2xl space-y-4 rounded-lg border border-border bg-background/40 p-4">
                      <div className="flex items-center justify-between gap-4">
                        <span className="text-sm text-muted-foreground">Project Name</span>
                        <span className="text-sm font-medium">
                          {autoGeneratedName ? 'Agent-generated from prompt' : projectName || '—'}
                        </span>
                      </div>
                      <div className="flex items-center justify-between gap-4">
                        <span className="text-sm text-muted-foreground">Visibility</span>
                        <span className="text-sm font-medium capitalize">{visibility}</span>
                      </div>
                      <div className="flex items-center justify-between gap-4">
                        <span className="text-sm text-muted-foreground">Template</span>
                        <span className="text-sm font-medium">
                          {autoSelectTemplate
                            ? 'Auto select best template'
                            : (selectedTemplateInfo?.title ?? '—')}
                        </span>
                      </div>
                    </div>
                  </>
                )}

                <div className="flex max-w-2xl items-center justify-end gap-3 border-t pt-6">
                  {currentStep > 0 ? (
                    <Button variant="ghost" onClick={handleBack}>
                      Back
                    </Button>
                  ) : (
                    <Button asChild variant="destructive">
                      <Link href="/dashboard">Cancel</Link>
                    </Button>
                  )}

                  {currentStep < 2 ? (
                    <Button
                      disabled={
                        (currentStep === 0 && !canContinueFromDetails) ||
                        (currentStep === 1 && !canContinueFromTemplate)
                      }
                      className="min-w-[120px]"
                      onClick={handleContinue}
                    >
                      Continue
                    </Button>
                  ) : (
                    <Button
                      className="min-w-[140px]"
                      onClick={() => createProjectMutation.mutate()}
                      disabled={createProjectMutation.isPending}
                    >
                      {createProjectMutation.isPending ? 'Creating...' : 'Create Project'}
                    </Button>
                  )}
                </div>
              </div>
            </CardContent>
          </div>
        </Card>
      </div>
    </PageLayout>
  );
};
