import type { Deployment } from '@/shared/types';

export const MOCK_DEPLOYMENTS: Deployment[] = [
  {
    id: 'd-001',
    projectId: 'p-001',
    projectName: 'hyper-api-gateway',
    status: 'live',
    region: 'us-east-1',
    deployedAt: '2m ago',
    url: 'https://hyper-api-gateway.pytholit.app',
    buildDuration: 28,
  },
  {
    id: 'd-002',
    projectId: 'p-002',
    projectName: 'neural-processor-v2',
    status: 'deploying',
    region: 'eu-west-2',
    deployedAt: 'Just now',
    buildDuration: 12,
  },
  {
    id: 'd-003',
    projectId: 'p-003',
    projectName: 'legacy-data-pipe',
    status: 'stopped',
    region: 'us-west-1',
    deployedAt: '2d ago',
    url: 'https://legacy-data-pipe.pytholit.app',
    buildDuration: 45,
  },
  {
    id: 'd-004',
    projectId: 'p-004',
    projectName: 'crypto-bot-alpha',
    status: 'live',
    region: 'ap-northeast',
    deployedAt: '4h ago',
    url: 'https://crypto-bot-alpha.pytholit.app',
    buildDuration: 22,
  },
  {
    id: 'd-005',
    projectId: 'p-005',
    projectName: 'auth-service-beta',
    status: 'failed',
    region: 'us-east-1',
    deployedAt: '1h ago',
    buildDuration: 120,
  },
];
